<a href="https://colab.research.google.com/github/ShubhamD-Genzeon/AI_ML_Training_2024/blob/main/Crop_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import classification_report
import seaborn as sns
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, roc_auc_score


In [15]:
dataset = pd.read_csv('Crop_recommendation.csv')

In [16]:
dataset.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [17]:
dataset.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [18]:
total_rows = dataset.shape[0]
total_rows

2200

In [19]:
unique_crops = dataset['label'].unique()
print("Unique crop types :")
for crop in unique_crops:
  print(crop)

Unique crop types :
rice
maize
chickpea
kidneybeans
pigeonpeas
mothbeans
mungbean
blackgram
lentil
pomegranate
banana
mango
grapes
watermelon
muskmelon
apple
orange
papaya
coconut
cotton
jute
coffee


In [20]:
from sklearn.preprocessing import LabelEncoder

# Extract the crop labels column from the dataset
crop_labels = dataset['label']

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform label encoder on crop labels
encoded_labels = label_encoder.fit_transform(crop_labels)

# Assign the encoded labels back to the last column of the dataset
dataset.iloc[:, -1] = encoded_labels


# Create a DataFrame with 'label' and 'Encoded_Crop_Labels' columns
encoded_df = pd.DataFrame({'label': crop_labels, 'Encoded_Crop_Labels': encoded_labels})

# Print unique values of 'label' and 'Encoded_Crop_Labels' columns
print(encoded_df.drop_duplicates())



            label  Encoded_Crop_Labels
0            rice                   20
100         maize                   11
200      chickpea                    3
300   kidneybeans                    9
400    pigeonpeas                   18
500     mothbeans                   13
600      mungbean                   14
700     blackgram                    2
800        lentil                   10
900   pomegranate                   19
1000       banana                    1
1100        mango                   12
1200       grapes                    7
1300   watermelon                   21
1400    muskmelon                   15
1500        apple                    0
1600       orange                   16
1700       papaya                   17
1800      coconut                    4
1900       cotton                    6
2000         jute                    8
2100       coffee                    5


<ipython-input-20-f12afc63f61e>:13: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  dataset.iloc[:, -1] = encoded_labels


In [21]:
dataset.head(100)

N   P   K  temperature   humidity        ph    rainfall  label
0   90  42  43    20.879744  82.002744  6.502985  202.935536     20
1   85  58  41    21.770462  80.319644  7.038096  226.655537     20
2   60  55  44    23.004459  82.320763  7.840207  263.964248     20
3   74  35  40    26.491096  80.158363  6.980401  242.864034     20
4   78  42  42    20.130175  81.604873  7.628473  262.717340     20
..  ..  ..  ..          ...        ...       ...         ...    ...
95  88  46  42    22.683191  83.463583  6.604993  194.265172     20
96  93  47  37    21.533463  82.140041  6.500343  295.924880     20
97  60  55  45    21.408658  83.329319  5.935745  287.576694     20
98  78  35  44    26.543481  84.673536  7.072656  183.622266     20
99  65  37  40    23.359054  83.595123  5.333323  188.413665     20

[100 rows x 8 columns]

In [22]:
X = dataset.iloc[:,:7].values
y = dataset.iloc[:,-1].values


In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X , y, test_size= 0.25, random_state = 0)


In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [25]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 3, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
RandomForestClassifier(criterion='entropy', n_estimators=3, random_state=0)
# from sklearn.tree import DecisionTreeClassifier
# classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
# classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3, random_state=0)

In [26]:
print(classifier.predict(sc.transform([[105,	14,	50,	26.2148837,	87.6883982,	6.419052193,	59.65590798	]])))

[21]


In [27]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[21 21]
 [21 21]
 [ 7  7]
 ...
 [ 5  5]
 [ 4  4]
 [19 19]]


In [28]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 16  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 24  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  1  0  0  0  0  0  0  1  0  0 25  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

0.9836363636363636